console.log("Array numérica");
var numbers = [1, 2, 3];
numbers.push(5);
console.log(numbers[2]);
console.log("=====================");
console.log("Array string");
var nomes = ['Matheus', 'André'];
console.log(typeof (nomes), nomes);
console.log("=====================");
console.log("outra sintaxe de array");
var nums = [100];
nums.push(200);
console.log(nums[1]);
