var x = 10;
console.log(x);
x = 16;
console.log(x);
console.log("x: " + typeof x);
var y = 15.4963;
console.log("y: " + typeof y);
console.log(y);
console.log(y.toPrecision(3));
console.log(y.toFixed(2));
console.log(y.toExponential(2));
